services:
  - type: web
    name: whatsapp-mcp
    env: docker
    repo: https://github.com/TharanaBope/whatsapp-mcp-n8n.git  # Update this to your actual GitHub repo
    buildCommand: ""  # Docker builds automatically
    startCommand: ""  # Docker starts automatically
    envVars:
      - key: PORT
        value: 8000
    plan: free  # Using free tier